SevenTag\Api\SecurityBundle\Entity\AuthCode:
    type: entity
    table: oauth2_auth_code
    repositoryClass: SevenTag\Api\SecurityBundle\Entity\AuthCodeRepository
    manyToOne:
        client:
            targetEntity: SevenTag\Api\SecurityBundle\Entity\Client
            joinColumn:
                nullable: false
                onDelete: CASCADE
                onUpdate: CASCADE
        user:
            targetEntity: SevenTag\Api\UserBundle\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: id
                onDelete: CASCADE
                onUpdate: CASCADE
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
