SevenTag\Api\SecurityBundle\Entity\Integration:
    type: entity
    repositoryClass: SevenTag\Api\SecurityBundle\Entity\IntegrationRepository
    manyToOne:
        user:
            cascade: ['persist', 'remove']
            targetEntity: SevenTag\Api\UserBundle\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: id
                onDelete: CASCADE
                onUpdate: CASCADE
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
