SevenTag\Api\SecurityBundle\Entity\RefreshToken:
    type: entity
    table: oauth2_refresh_token
    repositoryClass: SevenTag\Api\SecurityBundle\Entity\RefreshTokenRepository
    manyToOne:
        client:
            targetEntity: SevenTag\Api\SecurityBundle\Entity\Client
            joinColumn:
                nullable: false
                onDelete: CASCADE
                onUpdate: CASCADE
        user:
            targetEntity: SevenTag\Api\UserBundle\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: id
                onDelete: CASCADE
                onUpdate: CASCADE
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
