SevenTag\Api\TriggerBundle\Entity\Trigger:
  constraints:
      - SevenTag\Api\TriggerBundle\Validator\Constraints\TriggerType:
          groups: [Strict]
      - SevenTag\Api\TriggerBundle\Validator\Constraints\TriggerStrategy:
          groups: [Strict]
      - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
          fields: [name, container]
          errorPath: name
          message: 'This name is already in use. Trigger name in certain container should be unique.'
          repositoryMethod: findByNameAmongDrafts
  group_sequence:
    - Trigger
    - Strict
  properties:
    name:
      - NotBlank: ~
      - NotNull: ~
    container:
      - NotNull: ~
    type:
      - NotNull: ~
      - Type:
          type: integer
    strategy:
      - NotNull: ~
      - Type:
          type: integer
    conditions:
      - Valid: ~

SevenTag\Api\TriggerBundle\Entity\Condition:
  properties:
    variable:
      - NotBlank: ~
      - NotNull: ~
      - Length:
          max: 255
    condition:
      - NotBlank: ~
      - NotNull: ~
      - Length:
          max: 255
    value:
      - NotBlank: ~
      - NotNull: ~
      - Length:
          max: 255
    trigger:
      - NotNull: ~