fos_rest:
    param_fetcher_listener: true
    body_listener:
        decoders:
            json: fos_rest.decoder.json
    format_listener: true
    body_converter:
        enabled: true
        validate: false
    view:
        formats:
            json: true
            xml: false
        failed_validation: HTTP_BAD_REQUEST
        view_response_listener: 'force'
    routing_loader:
        default_format: json
        include_format: true
    format_listener:
        rules:
            - { path: '^/api',  priorities: ['json'], fallback_format: json, prefer_extension: false }
    serializer:
        serialize_null: true
