FOS\UserBundle\Model\User:
  exclusion_policy: None
  properties:
    id:
      expose: true
      groups: [users, integration, integrations]
    username:
      expose: true
      groups: [users]
    email:
      expose: true
      groups: [users, integration]
    roles:
      expose: true
      groups: [users, integration, integrations]
      access_type: public_method
      accessor:
        getter: getRoles
        setter: setRoles
    enabled:
      expose: true
      groups: [users, integration, integrations]
      serialized_name: status