parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: seventag1
    database_user: seventag
    database_password: QdXrga5FdpN2Xosp
    database_path: null
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    mailer_sender: example@example.com
    mailer_spool: { type: file, path: '%kernel.root_dir%/../var/spool' }
    mailer_delivery_address: null
    locale: en
    secret: '&-2_W\$/N=auNLuE?NM6:G:w-V{5,_'
    datetime_default_format: 'Y-m-d\TH:i:sO'
    seventag_licence_template_path: '%kernel.root_dir%/Resources/container-lib/licence.dist'
    seventag_tagtree_template_path: '%kernel.root_dir%/Resources/container-lib/tagTree.js.dist'
    seventag_containerjs_config_path: '%kernel.root_dir%/Resources/container-lib/containerjsConfig.js.dist'
    seventag_javascript_debugger_path: '%kernel.root_dir%/../web/container-debugger/debug.js'
    seventag_domain: //yourseventag.com
    seventag_javascript_library_path: '%kernel.root_dir%/Resources/container-lib/library.js.dist'
    seventag_javascript_bootstrap_path: '%kernel.root_dir%/Resources/container-lib/bootstrap.js.dist'
    seventag_javascript_cache_dir: '%kernel.root_dir%/../web/containers'
    seventag_javascript_url_template: //yourcdnhostname.com/containers/@id@.js
    seventag_container_library_cdn: { enabled: false, service: null, service_options: {  } }
    sentry_dsn: null
    web_dir: '%kernel.root_dir%/../web'
    seventag_noscript_backend: sonata.notification.backend.runtime
    oauth2_secret: 49dsi2td1fi84cwo0c008wkc0k04cgoow8ss4ock80c44ckg00
    random_id: 3fyzytq7aayogkcswokkss0ksoo4g4c4soocsc88wogccs88ks