SevenTag\Api\VariableBundle\Entity\Variable:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
        fields: [name, container]
        errorPath: name
        message: 'This name is already in use. Tag name in certain container should be unique.'
        repositoryMethod: findByNameAmongDrafts
  properties:
    name:
      - NotBlank: ~
      - Length:
          max: 256
