SevenTag\Component\Container\Model\Container:
  exclusion_policy: All
  accessor_order: custom
  custom_accessor_order: [accessId, name, description, tags, triggers, websites, code, version, delay, createdAt, updatedAt, getPublishedAt, hasUnpublishedChanges, permissionMask]
  virtual_properties:
    getPublishedAt:
      groups: [version_details]
    hasUnpublishedChanges:
      groups: [version_details]
    getPermissions:
      serialized_name: permissions
      type: array
      groups: [permissions]
  properties:
    accessId:
      expose: true
      groups: [container, containers]
      serialized_name: id
      type: integer
    name:
      expose: true
      groups: [container, containers]
    code:
      expose: true
      groups: [container]
    description:
      expose: true
      groups: [container, containers]
    tags:
      expose: true
      groups: [tags]
    triggers:
      expose: true
      groups: [triggers]
    websites:
      expose: true
      groups: [container, containers]
    version:
      expose: true
      groups: [version]
    delay:
      expose: true
      groups: [container]
    createdAt:
      expose: true
      groups: [container, containers]
    updatedAt:
      expose: true
      groups: [container, containers]