SevenTag\Api\TagBundle\Entity\Tag:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
        fields: [name, container]
        errorPath: name
        message: 'This name is already in use. Tag name in certain container should be unique.'
        repositoryMethod: findByNameAmongDrafts
    - SevenTag\Api\TagBundle\Validator\Constraints\TagTemplate: ~
  properties:
    name:
      - NotBlank: ~
      - Length:
          max: 256
    noScriptUri:
      - Url: ~
    documentWrite:
      - Type:
          type: boolean
    disableInDebugMode:
      - Type:
          type: boolean
    respectVisitorsPrivacy:
      - Type:
          type: boolean
