SevenTag\Api\ContainerBundle\Entity\ContainerPermission:
  properties:
    permissions:
      - NotBlank:
          groups: ['Permissions']
    user:
      - NotBlank:
          groups: ['Permissions']
      - Valid: ~
      - SevenTag\Api\ContainerBundle\Validator\Constraints\GrantPermissionsUser:
          groups: ['Permissions']

SevenTag\Api\ContainerBundle\Entity\Container:
  properties:
    name:
      - NotBlank: ~
      - Length:
          max: 256
