SevenTag\Component\Condition\Model\Condition:
  exclusion_policy: all
  accessor_order: custom
  custom_accessor_order: [variable, condition, value, createdAt, updatedAt]
  properties:
    variable:
      expose: true
      groups: [conditions]
    condition:
      expose: true
      groups: [conditions]
    value:
      expose: true
      groups: [conditions]