jms_serializer:
  handlers:
    datetime:
      default_format: "%datetime_default_format%"
  metadata:
    auto_detection: true
    directories:
      SevenTagComponentContainer:
        namespace_prefix: "SevenTag\\Component\\Container"
        path: "@SevenTagContainerBundle/Resources/config/serializer/component"
      SevenTagComponentTag:
        namespace_prefix: "SevenTag\\Component\\Tag"
        path: "@SevenTagTagBundle/Resources/config/serializer/component"
      SevenTagComponentTrigger:
        namespace_prefix: "SevenTag\\Component\\Trigger"
        path: "@SevenTagTriggerBundle/Resources/config/serializer"
      SevenTagVariableBundle:
        namespace_prefix: "SevenTag\\Component\\Variable"
        path: "@SevenTagVariableBundle/Resources/config/serializer/component"
      SevenTagComponentCondition:
        namespace_prefix: "SevenTag\\Component\\Condition"
        path: "@SevenTagTriggerBundle/Resources/config/serializer"
      SevenTagAppBundle:
        namespace_prefix: "SevenTag\\AppBundle"
        path: "@SevenTagAppBundle/Resources/config/serializer"
      FosUserBundleModel:
        namespace_prefix: "FOS\\UserBundle"
        path: "@SevenTagUserBundle/Resources/config/serializer/fos"
      SevenTagUserBundle:
        namespace_prefix: "SevenTag\\UserBundle"
        path: "@SevenTagUserBundle/Resources/config/serializer"
      SevenTagContainerBundle:
        namespace_prefix: "SevenTag\\ContainerBundle"
        path: "@SevenTagContainerBundle/Resources/config/serializer"
      SevenTagTagBundle:
        namespace_prefix: "SevenTag\\TagBundle"
        path: "@SevenTagTagBundle/Resources/config/serializer"
      SevenTagSecurityBundle:
        namespace_prefix: "SevenTag\\SecurityBundle"
        path: "@SevenTagSecurityBundle/Resources/config/serializer"
      FOSOAuthServerBundle:
        namespace_prefix: "FOS\\OAuthServerBundle"
        path: "@SevenTagSecurityBundle/Resources/config/serializer/fos"
