SevenTag\Api\UserBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [email]
            groups: [Create, CreateIntegration]
            message: "This email address has been used previously before"
    properties:
        firstName:
            - NotBlank: { groups: [Create, Edit, Me] }
            - Length:
                max: 256
                groups: [Create, Edit]
        lastName:
            - NotBlank: { groups: [Create, Edit, Me] }
            - Length:
                max: 256
                groups: [Create, Edit]
        language:
            - NotBlank: { groups: [OthersSettings] }
        plainPassword:
            - Length:
                min: 8
                minMessage: "Your password must have at least {{ limit }} characters."
                max: 255
                maxMessage: "Your password is too long."
                groups: [Create, Edit, Resetting, ChangePassword]
            - NotBlank:
                message: "Please enter a password"
                groups: [Resetting, ChangePassword]
        email:
            - NotBlank: { groups: [Create, CreateIntegration] }
            - Email: { groups: [Create, CreateIntegration] }
        roles:
           - SevenTag\Api\UserBundle\Validator\Roles:
                multiple: true
                groups: [Create, Edit]

FOS\UserBundle\Form\Model\ResetPassword:
    properties:
        new:
            - Length:
                min: 8
                minMessage: "Your password must have at least {{ limit }} characters."
                max: 255
                maxMessage: "Your password is too long."
            - NotBlank:
                message: "Please enter a password"
