SevenTag\Api\AppBundle\Entity\Version:
    type: entity
    table: version
    repositoryClass: SevenTag\Api\AppBundle\Entity\VersionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        createdBy:
            targetEntity: SevenTag\Api\UserBundle\Entity\User
            joinColumn:
                name: created_by
                referencedColumnName: id
                onDelete: CASCADE
                onUpdate: CASCADE
    fields:
        published:
            type: boolean
            column: published
        draft:
            type: boolean
            column: draft
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    lifecycleCallbacks: {  }
