SevenTag\Component\Variable\Model\Variable:
    exclusion_policy: None
    virtual_properties:
        getContainerAccessId:
            serialized_name: container
            type: integer
            groups: [variable]
    accessor_order: custom
    custom_accessor_order: [accessId, name, description, type, value, options, updated_at, created_at]
    properties:
        accessId:
            expose: true
            serialized_name: id
            type: integer
            groups: [variables, variable]
        name:
            expose: true
            groups: [variables, variable, containerVariable]
        description:
            expose: true
            groups: [variables, variable]
        type:
            expose: true
            groups: [variables, variable, variableType, containerVariable]
        value:
            expose: true
            groups: [variables, variable, containerVariable]
        options:
            expose: true
            groups: [variables, variable, containerVariable]
        updatedAt:
            expose: true
            groups: [variables, variable]
        createdAt:
            expose: true
            groups: [variables, variable]


